# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namex', models.CharField(max_length=220)),
                ('descriptionx', models.CharField(max_length=520)),
                ('ownerx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagsx', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
